#!/bin/bash

cmd_help() {
    echo "AI Dev Sandbox - Ephemeral worktree-based development environments"
    echo ""
    echo "Usage: $0 <command> [args]"
    echo ""
    echo "Commands:"
    echo "  new <repo> [branch] [from] [options]  Create sandbox from repo"
    echo "  new --last                            Repeat last cast new command"
    echo "  new --preset <name>                   Use a saved preset"
    echo "  repeat                                Alias for 'new --last'"
    echo "  preset list                           List saved presets"
    echo "  preset show <name>                    Show preset details"
    echo "  preset delete <name>                  Delete a preset"
    echo "  list [--json]                         List all sandboxes"
    echo "  attach <name>                         Attach to a sandbox"
    echo "  start <name>                          Start a stopped sandbox"
    echo "  stop <name>                           Stop a sandbox (keeps worktree)"
    echo "  destroy <name> [-f] [-y]              Destroy sandbox and worktree (confirms first)"
    echo "  destroy-all                           Destroy all sandboxes (double confirmation)"
    echo "  build                                 Build/rebuild the sandbox image"
    echo "  config [--json]                       Show config and checks"
    echo "  prune [-f] [--json]                   Remove orphaned configs"
    echo "  status [name] [--json]                Show sandbox status"
    echo "  info [--json]                         Show config + status"
    echo "  upgrade [--local]                     Upgrade to latest version"
    echo "  help                                  Show this help"
    echo ""
    echo "New sandbox options:"
    echo "  --mount, -v src:dst[:ro]              Mount host path into container"
    echo "  --copy, -c src:dst                    Copy host path into container (once at creation)"
    echo "  --network, -n <mode>                  Network isolation: limited, host-only, none"
    echo "  --with-ssh                            Enable SSH agent forwarding"
    echo "  --with-opencode                       Enable OpenCode setup"
    echo "  --with-zai                            Enable ZAI Claude alias"
    echo "  --no-isolate-credentials              Pass API keys directly (disable isolation)"
    echo "  --wd <path>                           Working directory within repo"
    echo "  --sparse                              Enable sparse checkout (requires --wd)"
    echo "  --pip-requirements, -r <path>         Install Python packages"
    echo "  --allow-pr                            Allow PR operations"
    echo "  --save-as <name>                      Save this configuration as a preset"
    echo "  --with-ide[=name]                     Launch IDE (cursor, zed, code) then terminal"
    echo "  --ide-only[=name]                     Launch IDE only, skip terminal"
    echo "  --no-ide                              Skip IDE selection prompt"
    echo ""
    echo "Examples:"
    echo "  $0 new user/repo                              # checkout main"
    echo "  $0 new .                                      # use current repo/branch"
    echo "  $0 new user/repo feature-branch               # checkout existing branch"
    echo "  $0 new user/repo my-feature main              # new branch from main"
    echo "  $0 new user/repo feat --wd packages/app       # monorepo subdirectory"
    echo "  $0 new user/repo feat --save-as myproject     # save as preset"
    echo "  $0 new --preset myproject                     # use saved preset"
    echo "  $0 new --last                                 # repeat last command"
    echo "  $0 repeat                                     # same as above"
    echo "  $0 attach repo-feature-branch"
    echo "  $0 list"
}
