#!/bin/bash

cmd_help() {
    echo "AI Dev Sandbox - Ephemeral worktree-based development environments"
    echo ""
    echo "Usage: $0 <command> [args]"
    echo ""
    echo "Commands:"
    echo "  new <repo> [branch] [from] [--mount|-v src:dst] [--copy|-c src:dst] [--network|-n mode]"
    echo "                            [--with-ssh] [--with-api-keys] [--no-api-keys]"
    echo "                            Create new sandbox from repo/branch"
    echo "  list [--json]             List all sandboxes"
    echo "  attach <name>             Attach to a sandbox"
    echo "  start <name>              Start a stopped sandbox"
    echo "  stop <name>               Stop a sandbox (keeps worktree)"
    echo "  destroy <name> [-f] [-y]  Destroy sandbox and worktree (confirms first)"
    echo "  destroy-all               Destroy all sandboxes (double confirmation)"
    echo "  build                     Build/rebuild the sandbox image"
    echo "  config [--json]           Show config and checks"
    echo "  prune [-f] [--json]       Remove orphaned configs"
    echo "  status [name] [--json]    Show sandbox status"
    echo "  info [--json]             Show config + status"
    echo "  help                      Show this help"
    echo ""
    echo "Examples:"
    echo "  $0 new user/repo                      # checkout main"
    echo "  $0 new .                              # use current repo/branch"
    echo "  $0 new user/repo feature-branch       # checkout existing branch"
    echo "  $0 new user/repo my-feature main      # new branch from main"
    echo "  $0 new user/repo feat --mount /data:/data  # with extra mount"
    echo "  $0 new user/repo feat --copy ~/models:/models  # copy into container"
    echo "  $0 new user/repo feat --network=full           # full network access"
    echo "  $0 new user/repo feat --no-api-keys            # skip syncing ~/.api_keys"
    echo "  $0 attach repo-feature-branch"
    echo "  $0 list"
}
