#!/bin/bash

SANDBOX_HOME="${SANDBOX_HOME:-$HOME/.sandboxes}"
REPOS_DIR="$SANDBOX_HOME/repos"
WORKTREES_DIR="$SANDBOX_HOME/worktrees"
CLAUDE_CONFIGS_DIR="$SANDBOX_HOME/claude-config"

if [ -z "${SCRIPT_DIR:-}" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi

DOCKER_IMAGE="foundry-sandbox:latest"
# Container user - set via SANDBOX_USERNAME at build time, defaults to ubuntu
CONTAINER_USER="${CONTAINER_USER:-ubuntu}"
# Home is always /home/ubuntu (tmpfs mount) - user's home is symlinked there
CONTAINER_HOME="/home/ubuntu"
SSH_AGENT_CONTAINER_SOCK="/ssh-agent"
CONTAINER_OPENCODE_PLUGIN_DIR="$CONTAINER_HOME/.config/opencode/plugins"

SANDBOX_DEBUG="${SANDBOX_DEBUG:-0}"
SANDBOX_VERBOSE="${SANDBOX_VERBOSE:-0}"
SANDBOX_ASSUME_YES="${SANDBOX_ASSUME_YES:-0}"

# Network mode: limited, host-only, none (full mode removed for security)
SANDBOX_NETWORK_MODE="${SANDBOX_NETWORK_MODE:-limited}"

# Credential sync toggles (0 = disabled, 1 = enabled)
SANDBOX_SYNC_ON_ATTACH="${SANDBOX_SYNC_ON_ATTACH:-0}"
SANDBOX_SYNC_SSH="${SANDBOX_SYNC_SSH:-0}"
SANDBOX_SSH_MODE="${SANDBOX_SSH_MODE:-always}"
SANDBOX_OPENCODE_DISABLE_NPM_PLUGINS="${SANDBOX_OPENCODE_DISABLE_NPM_PLUGINS:-1}"
SANDBOX_OPENCODE_PLUGIN_DIR="${SANDBOX_OPENCODE_PLUGIN_DIR:-}"
SANDBOX_OPENCODE_PREFETCH_NPM_PLUGINS="${SANDBOX_OPENCODE_PREFETCH_NPM_PLUGINS:-1}"
SANDBOX_OPENCODE_DEFAULT_MODEL="${SANDBOX_OPENCODE_DEFAULT_MODEL:-openai/gpt-5.2-codex}"
SANDBOX_TMUX_SCROLLBACK="${SANDBOX_TMUX_SCROLLBACK:-200000}"
SANDBOX_TMUX_MOUSE="${SANDBOX_TMUX_MOUSE:-0}"
